### ISSUE TITLE
JDK installed in wrong directory on Windows

### ISSUE THREAD

**Issue by HedgehogCode** [conda-forge/openjdk-feedstock#107]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In https://github.com/conda-forge/openjdk-feedstock/commit/5f998d401e4d97c50dc24aa2177945e655a4833c the `JAVA_HOME` changed to `<env_root>\Library\lib\jvm`. However, the JVM is still installed in `<env_root>\Library`. This causes problems with applications that rely on the `JAVA_HOME` variable which now points to a location that does not exist. See the below example where I tried to use maven but it only succeeded after I changed the `JAVA_HOME` to `<env_root>\Library` manually (not that the build failure is expected and shows that maven is working).

I noticed that the commit linked above did not adapt the [`recipe/bld.bat`](https://github.com/conda-forge/openjdk-feedstock/blob/java11/recipe/bld.bat) file to install the library to the new location.

Demo:
```
(openjdk-env) C:\Users\benjamin>java -version
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)

(openjdk-env) C:\Users\benjamin>echo %JAVA_HOME%
C:\Users\benjamin\miniconda3\envs\openjdk-env\Library\lib\jvm

(openjdk-env) C:\Users\benjamin>dir %JAVA_HOME%
 Volume in drive C has no label.
 Volume Serial Number is 6AB3-226D

 Directory of C:\Users\benjamin\miniconda3\envs\openjdk-env\Library\lib

File Not Found

(openjdk-env) C:\Users\benjamin>mvn
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE

(openjdk-env) C:\Users\benjamin>set JAVA_HOME=C:\Users\benjamin\miniconda3\envs\openjdk-env\Library

(openjdk-env) C:\Users\benjamin>mvn
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.126 s
[INFO] Finished at: 2022-09-28T13:55:29+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
```

### Installed packages

```shell
# packages in environment at C:\Users\benjamin\miniconda3\envs\openjdk-env:
#
# Name                    Version                   Build  Channel
maven                     3.8.1                haa95532_0
openjdk                   11.0.15              h57928b3_2    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vs2015_runtime            14.29.30139          h890b9b1_7    conda-forge
```

### Environment info

```shell
active environment : openjdk-env
    active env location : C:\Users\benjamin\miniconda3\envs\openjdk-env
            shell level : 2
       user config file : C:\Users\benjamin\.condarc
 populated config files :
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\benjamin\miniconda3  (writable)
      conda av data dir : C:\Users\benjamin\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\benjamin\miniconda3\pkgs
                          C:\Users\benjamin\.conda\pkgs
                          C:\Users\benjamin\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\benjamin\miniconda3\envs
                          C:\Users\benjamin\.conda\envs
                          C:\Users\benjamin\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by christophfink** [comment]
We’re facing the same issue, this relates issue #86, that has been resolved in PR #100 for other versions, and supposedly should have been fixed in #106 for OpenJDK 11. This currently overwrites DLLs installed by other packages (zip, freetype).

**Comment by christophfink** [comment]
This seems to affect other versions, as well, for instance, OpenJDK 17.

**Comment by beenje** [comment]
I have the same issue:

```
(java-dev) C:\Users\beenj>conda list
# packages in environment at C:\Users\beenj\mambaforge\envs\java-dev:
#
# Name                    Version                   Build  Channel
maven                     3.8.6                h57928b3_0    conda-forge
openjdk                   11.0.15              h57928b3_2    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vs2015_runtime            14.29.30139          h890b9b1_8    conda-forge

(java-dev) C:\Users\beenj>mvn -version
The JAVA_HOME environment variable is not defined correctly,
this environment variable is needed to run this program.
```

Looks like https://github.com/conda-forge/openjdk-feedstock/pull/106 didn't fix the problem for openjdk 11?

**Comment by izahn** [comment]
Yeah, this is definitely a bug in the windows build, sorry I haven't had time to look into it yet. I will eventually, or PR's welcome if someone else want's to take a shot at it.

Best,
Ista

**Comment by h-vetinari** [comment]
CC @Hoeze since #100 / #105 were your PRs that are were causing breakage on windows in several feedstocks, and have been marked broken in https://github.com/conda-forge/admin-requests/pull/498

**Comment by h-vetinari** [comment]
> CC @Hoeze since #100 / #105 were your PRs that are were causing breakage on windows in several feedstocks, and have been marked broken in [conda-forge/admin-requests#498](https://github.com/conda-forge/admin-requests/pull/498)

Hey, cool that you've seen the message. I pinged you for two reasons (aside from letting you know):
* the change you made is not available anymore, hence the rationale of #100 ("This PR fixes issues with colliding packages [...]") is open again.
* the repo is now in a sort-of in-between state - any new release from the main / `java11` branches will again cause breakage, and would similarly need to be marked broken.

So either we should: fully revert the changes of #100 / #105 (so that the feedstock can publish packages again), or improve the fix from #100 in such a way that it doesn't break other packages.

As the author of that change, you're the most obvious person to ask which one of these is more likely/reasonable. If you cannot do either, then it'll just be a straight revert.

CC @conda-forge/openjdk

**Comment by izahn** [comment]
> > CC @Hoeze since #100 / #105 were your PRs that are were causing breakage on windows in several feedstocks, and have been marked broken in [conda-forge/admin-requests#498](https://github.com/conda-forge/admin-requests/pull/498)
> 
> Hey, cool that you've seen the message. :) I pinged you for two reasons (aside from letting you know):
> 
>     * the change you made is not available anymore, hence the rationale of [Move libraries to /lib/jvm #100](https://github.com/conda-forge/openjdk-feedstock/pull/100) ("This PR fixes issues with colliding packages [...]") is open again.

On windows you mean right? The Linux packages are not broken and are still available.

> 
>     * the repo is now in a sort-of in-between state - any new release from the main / `java11` branches will again cause breakage, and would similarly need to be marked broken.

Again, on windows only.

> 
> 
> So either we should: fully revert the changes of #100 / #105 (so that the feedstock can publish packages again), or improve the fix from #100 in such a way that it doesn't break other packages.

We should definitely not fully revert the change. The change fixed long-standing brokenness and was badly needed.
> 
> As the author of that change, you're the most obvious person to ask which one of these is more likely/reasonable. If you cannot do either, then it'll just be a straight revert.

https://github.com/conda-forge/openjdk-feedstock/pull/100 was approved by my and merged by @xhochy so the responsibility is broadly shared. It is not necessarily @Hoeze 's responsibility to fix it. Furthermore, we should definitely not revert the entire change, only the Windows part, and only that as a last resort because doing so will result in brokenness of another kind, i.e., the kind reported in https://github.com/conda-forge/openjdk-feedstock/issues/86

> 
> CC @conda-forge/openjdk

**Comment by h-vetinari** [comment]
> #100 was approved by my and merged by @xhochy so the responsibility is broadly shared. It is not necessarily @Hoeze 's responsibility to fix it. Furthermore, we should definitely not revert the entire change, only the Windows part, and only that as a last resort because doing so will result in brokenness of another kind, i.e., the kind reported in #86

There was no accusation implied, just that someone needs to do _something_. It's standard procedure (in many, many projects, not specific to conda-forge) that changes which break other components/consumers/projects are reverted - no harm done, try again.

Assuming people were aware of the breakage, marking the builds from #100 as broken should have happened IMO much sooner though; as an example, a bunch of java builds broke on feedstocks that I co-maintain, but I had no idea where it was coming from (cryptic `JAVA_HOME` not found), until @xhochy pointed me here. Some of those feedstocks were in limbo for over a month - and that's just not a very sustainable way to deal with such changes from an ecosystem POV.

I get that this is FOSS, we're all super busy, and probably overworked. So no-one can demand a more elaborate fix of anyone. But barring someone willing to come up with a better fix, a revert is the only reasonable option. Otherwise, the next migrator comes along again, the CI looks green, someone forgets this discussion and pushes merge, and all those other feedstocks break again.

None of this is in any way meant confrontationally; mistakes happen. The point I'm making is not to leave others hanging in that fragile state while you intend to fix the breakage (unless the time horizon is very short, e.g. <24h for a project like LLVM, maybe a couple of days for conda-forge). Revert, adapt, redeploy.

**Comment by izahn** [comment]
I know this breakage has been frustrating, and I'm sorry we didn't get a fix out sooner. There's a longer arc to the story though. Basically openjdk has been broken for years because it installs it's own copy of `libzip` that conflicts with the one provided by the `libzip` package. We finally got that fixed (on Linux at least), and that is a necessary and important improvement. We should try to fix the windows builds in a way that doesn't re-introduce the original problem, though I'm not really sure how to do it. Work and discussion about that is being done in https://github.com/conda-forge/openjdk-feedstock/pull/108 and I'll appreciate any help we can get there.

**Comment by xhochy** [comment]
I'm not sure currently which of the `libzip.dll` is at fault. Is the OpenJDK one missing symbols (i.e. we should never use that and always rely on the `libzip` one) or is the `libzip` provided one missing these symbols (i.e. we should get them exported there)?

**Comment by izahn** [comment]
> I'm not sure currently which of the `libzip.dll` is at fault. Is the OpenJDK one missing symbols (i.e. we should never use that and always rely on the `libzip` one) or is the `libzip` provided one missing these symbols (i.e. we should get them exported there)?

I took a quick look and the two versions of `libzip.so` (provided by `libzip` and `openjdk` respectively) look totally different. 

Basically conda-forge is the only packaging ecosystem I know of that doesn't put openjdk in a separate directory, e.g, https://packages.ubuntu.com/jammy/amd64/openjdk-11-jre-headless/filelist , https://archlinux.org/packages/extra/x86_64/jre-openjdk-headless/ . IMO the approach taken in https://github.com/conda-forge/openjdk-feedstock/pull/100 is the standard and correct approach to java packaging, we just got hung up on the fact that we can't make soft links on Windows...

**Comment by xhochy** [comment]
I'm scared with modifying `PATH` in activation scripts but OK with the approach posted in https://github.com/conda-forge/openjdk-feedstock/pull/108#issuecomment-1290593170

**Comment by izahn** [comment]
If someone can provide a simple way to trigger this bug we can add it to the package checks. I tried https://github.com/conda-forge/openjdk-feedstock/pull/110/commits/9c16a5f68eb41058bb1ecb39fd1c4f4fbe106885 but oddly it works...

**Comment by mbargull** [comment]
Port from gh-108 to `main` at gh-112.

**Comment by h-vetinari** [comment]
I think this might still end up breaking certain things?

Seen in https://github.com/conda-forge/bazel-feedstock/pull/159
```
+ JNI_HEADERS_DIR=C:/t/tmp.Y3FC9afa0H/src/main/native
+ mkdir -p C:/t/tmp.Y3FC9afa0H/src/main/native
+ cp -f /d/bld/bazel_1666977165184/_h_env/Library/include/jni.h C:/t/tmp.Y3FC9afa0H/src/main/native/
cp: cannot stat '/d/bld/bazel_1666977165184/_h_env/Library/include/jni.h': No such file or directory
```

**Comment by mbargull** [comment]
> I think this might still end up breaking certain things?
> 
> Seen in [conda-forge/bazel-feedstock#159](https://github.com/conda-forge/bazel-feedstock/pull/159)
> 
> ```
> + JNI_HEADERS_DIR=C:/t/tmp.Y3FC9afa0H/src/main/native
> + mkdir -p C:/t/tmp.Y3FC9afa0H/src/main/native
> + cp -f /d/bld/bazel_1666977165184/_h_env/Library/include/jni.h C:/t/tmp.Y3FC9afa0H/src/main/native/
> cp: cannot stat '/d/bld/bazel_1666977165184/_h_env/Library/include/jni.h': No such file or directory
> ```

Nope, that one is set to fail:
https://github.com/conda-forge/bazel-feedstock/blob/6d1d7ef4d21ffb6ccd9af331efc38864efa4b18b/recipe/bld.bat#L20
(I can't tell you if there are more issues with the bazel recipe, but that was the obvious one I saw.)

**Comment by h-vetinari** [comment]
Thanks @mbargull! So what directory should this now point to? I'm unsure from looking at the diff in #112, and the bot hasn't populated https://github.com/regro/libcfgraph/tree/master/artifacts/openjdk/conda-forge with the new builds yet.

**Comment by mbargull** [comment]
> So what directory should this now point to?

(Now it's under `Library/lib/jvm`.)
BUT: It should just not mess with `JAVA_HOME`, i.e.,
```diff
-:: LIBRARY_PREFIX gets translated to '/' instead of the absolute path
-FOR /F "delims=" %%i IN ('cygpath.exe -u "%PREFIX%"') DO set "JAVA_HOME=%%i/Library"
+FOR /F "delims=" %%i IN ('cygpath.exe -u "%JAVA_HOME%"') DO set "JAVA_HOME=%%i"
```
like with the other env vars.
